apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: a-single-pod
    foo: bar
  name: hello
  namespace: default
spec:
  containers:
    - name: hello
      image: busybox
      command:
      - sh
      args:
      - -c 
      - "echo HI && tail -f /dev/null"
